version: '3.8'

services:
  api:
    build: .
    command: bash -c "uvicorn fastmongo:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example  
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
